### ISSUE TITLE
Scala.js 0.6.6 released

### ISSUE THREAD

**Issue by mariussoutier** [vmunier/sbt-play-scalajs#18]
Please upgrade:

http://www.scala-js.org/news/2016/01/25/announcing-scalajs-0.6.6/

**Comment by vmunier** [comment]
Hello,
If you use Scala.js `v0.6.6` in your project and sbt-play-scalajs uses `v0.6.5`, the sbt default conflict manager will select the newer version, `v0.6.6`.

**Comment by mariussoutier** [comment]
Yeah sure, but would be nice to get rid of the warning.

**Comment by vmunier** [comment]
sbt-play-scalajs `v0.2.9` has just been published and uses Scala.js `v0.6.6`.

**Comment by mariussoutier** [comment]
:+1: Thanks
