### ISSUE TITLE
Include jsdeps file

### ISSUE THREAD

**Issue by DennisVis** [vmunier/sbt-play-scalajs#5]
Scala.js has the ability to concatenate all JS dependencies into a jsdeps file. Currently this plugin does not take this file into account when moving the Scala.js files from the Scala.js projects to the server project. 

I for one would like to be able to use this file.

**Comment by DennisVis** [comment]
I have identified a possible fix for this issue. I'd like to test this, but can't seem to use a locally published version of the plugin due to cross-version problems. I'm using 2.11.5. Is there any special steps I have to take to make that work?

**Comment by sjrd** [comment]
An sbt plugin should always be compiled with Scala 2.10.x (2.10.4 usually), no matter what version of Scala your project uses.

**Comment by vmunier** [comment]
Hi, you can try the following change in `PlayScalaJS.scala`:
```
   def scalaJSOutput(optJS: TaskKey[Attributed[File]]): Initialize[Task[Seq[PathMapping]]] = Def.task {
-    onScalaJSProjectsCompile(optJS, packageScalaJSLauncher).value.map(_.data).flatMap { f =>
+    val output = onScalaJSProjectsCompile(packageJSDependencies).value ++ onScalaJSProjectsCompile(optJS, packageScalaJSLauncher).value.map(_.data)
+    output.flatMap { f =>
```

To publish the plugin locally, just use `sbt publishLocal`.

**Comment by DennisVis** [comment]
I added your suggested change, that was indeed the spot where I was working on.

Then I compiled and locally published the plugin. I can see it in my local ivy2 repo. I gave it a version number of 0.2.3 just for testing. I pointed the plugins.sbt file in my project to this new version like so:

```scala
addSbtPlugin("com.vmunier" % "sbt-play-scalajs" % "0.2.3")
```

I don' t get any dependency errors on start up, but keys like ScalaJSPlay are not being recognised. Any suggestions?

**Comment by vmunier** [comment]
> keys like ScalaJSPlay are not being recognised
What error do you have?

**Comment by DennisVis** [comment]
The following:

```
build.sbt:68: error: not found: value ScalaJSPlay
lazy val Project = (project in file("project-js")).enablePlugins(ScalaJSPlugin, ScalaJSPlay).settings(
                                                                                    ^
sbt.compiler.EvalException: Type error in expression
// Rest of stacktrace
[error] sbt.compiler.EvalException: Type error in expression
```

**Comment by Aste88** [comment]
I wish I had seen this earlier, it took me a while to figure out on my own (sbt is anything but simple).

I can confirm this works. Thanks!

**Comment by vmunier** [comment]
Hi, thanks for reporting the issue. You can now upgrade to `sbt-play-scalajs` v0.2.2 which calls `packageJSDependencies` :)

**Comment by DennisVis** [comment]
Works like a charm! Thank you for the fix, much appreciated!
